# Generated by Django 4.2.5 on 2023-10-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture_path',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures_path/'),
        ),
    ]
