# Generated by Django 4.2.5 on 2023-10-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_app', '0014_alter_user_location_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
